apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-env.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-dev.yml
    name: psychology-config