apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cluster-issuer.yaml

patches:
  - path: patch-env.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: psychology-config