apiVersion: apps/v1
kind: Deployment
metadata:
  name: psychology-service
  labels:
    app: psychology-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psychology-service
  template:
    metadata:
      labels:
        app: psychology-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9004"
    spec:
      containers:
        - name: psychology-service
          image: sunwoo3856/psychology-service
          ports:
            - containerPort: 9004
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5"]
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9004
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9004
            initialDelaySeconds: 20
            periodSeconds: 15
          volumeMounts:
            - name: psychology-config-volume
              mountPath: /config
      volumes:
        - name: psychology-config-volume
          configMap:
            name: psychology-config
